### ISSUE TITLE
Does the plugin provide a variable with the adblock result?

### ISSUE THREAD

**Issue by GitPuffy** [tailot/nodebb-plugin-adblock#2]
Does this plugin provide a "variable" from which I could determine if the user is visiting with or without adblock running?

I do not specifically wish to alert or stop a visitor from using my NodeBB forum if they are using an adblocker but I would like to record that in my Piwik analytics system.

For example, today I record my visiting user's username in Piwik by referencing the NodeBB variable `app.user.username`, does your plugin allow for access to such a variable which would record the visitor having or not having adblock enabled?

Thank you.

**Comment by tailot** [comment]
Nice idea! I changed the source code:

- I reference the variable app.user.adblock = true if adblock is enabled.   

- The message disappear if you do not enter text.

Regards.

Tailot

**Comment by GitPuffy** [comment]
I appreciate you adding this feature but I am not able to make it work.  I am getting a "undefined" when I try to reference the variable `app.user.adblock`. 

I went so far as to change the name of the variable (thinking that app.user.X was reserved to the NodeBB) to appuseradblock and now I get series of errors (when I use `console.log(appuseradblock)` to see the result of variable in my browser log.

Do you have any further suggestions on what may be wrong?  Have you been able to see the output of your variable?  A quick place to add `console.log(app.user.adblock);` would be to `Appearance > Custom HTML & CSS> Custom Header`

Thank you.
